#!/usr/bin/env node

var UhkConnection = require('./lib/UhkConnection');
var uhkConnection = new UhkConnection();
uhkConnection.connect(function() {
    uhkConnection.sendRequest(UhkConnection.COMMANDS.WRITE_EEPROM, 11, function() {
    });
});
